const PROFILE = {
  name: 'Yan Paing Kyaw',
  title: 'Chief Technology Officer',
  company: 'Mifida Microfinance Ltd.',
  location: 'Yangon, Myanmar',
  email: atob('eWFucGFpbmdreWF3QGdtYWlsLmNvbQ=='),
  phone: atob('KDk1KS00NDgwMDI0MTI='),
  address: atob('NjUzIFphck5pIDE0IFN0cmVldCwgU291dGggT2trYWxhcGEgVG93bnNoaXA='),
  summary:
    'A results-oriented leader with over seventeen years of experience in Information Technology, including software development (full SDLC), project management, and system integration. Proven team leader with strong programming, design, and analysis skills, combining leadership, analytical, and relational strengths to align technology strategy with business goals.',
  stats: [
    { label: 'Years Experience', value: 17, suffix: '+' },
    { label: 'Leadership Roles', value: 10, suffix: '+' },
    { label: 'Users Managed', value: 1.7, suffix: 'M', decimals: 1 },
  ],
  languages: [
    { name: 'Myanmar', level: 'Mother Tongue' },
    { name: 'English', level: 'Fluent' },
  ],
  experience: [
    {
      id: 'mifida',
      company: 'Mifida Microfinance Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Chief Technology Officer',
      start: '2024-09',
      end: 'Present',
      highlights: [
        'Lead the strategy for technology platforms, partnerships, and external relationships',
        'Identify, compare, select, and implement technology solutions to meet current and future needs',
        'Manage and optimize infrastructure assets to satisfy internal financial targets',
        'Create overall technology standards and practices and ensure adherence',
        'Ensure alignment between technology strategy and business strategy',
        'Routinely engage with C-level executives for strategy consulting',
        'Planning, scheduling, and budgeting for projects with technical solutions',
      ],
    },
    {
      id: 'atom',
      company: 'Atom Myanmar Pte Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Sr. Manager',
      start: '2022-06',
      end: '2024-09',
      highlights: [
        'Head of IT Delivery of Projects and Mobile App',
        'Managing multiple IT projects and scrum teams with quality delivery based on SLA',
        'Manage agile development team to deliver iOS, Android, and backend applications',
        'Managing 1.7 Million customer-facing applications running smoothly 24/7 with zero downtime',
        'Develop the digital roadmap and lead architecture and design',
        'Successfully led Project Fusion ERP Swap, ERP Migration on-premise to Cloud, Mobile Telecom Selfcare App',
      ],
    },
    {
      id: 'maha',
      company: 'Maha Microfinance Pte Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Head of IT',
      start: '2020-07',
      end: '2022-01',
      highlights: [
        'Re-organizing IT team to meet Maha Digital Initialize strategy and projects',
        'Train and recruit local IT team to align with Maha digital projects',
        'Liaising closely with technical and business stakeholders as a bridge between technology and the organization',
        'Set up required IT policy aligned with organization process and procedure',
        'Successfully led Solarwind Ticketing Management System and Data Lake Platform (POC)',
      ],
    },
    {
      id: 'hana',
      company: 'Hana Microfinance Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Head of IT',
      start: '2016-09',
      end: '2020-07',
      highlights: [
        'Developing and maintaining the approved ICT strategy in support of business objectives',
        'Planning and design for ICT infrastructure',
        'Hire and coach a local ICT team to provide an efficient and effective workforce',
        'Successfully led Finflux Core Banking System Implementation',
      ],
    },
    {
      id: 'early-dawn',
      company: 'Early Dawn Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Head of IT',
      start: '2015-05',
      end: '2016-09',
      highlights: [
        'Strategy and manage IT infrastructure setup for head office and branches',
        'Hire and coach a local IT & MIS team',
        'Manage IT budget to ensure resources are well utilized',
        'Successfully led Kredits Loan Tracking System Implementation',
      ],
    },
    {
      id: 'bc-finance',
      company: 'BC Finance Ltd.',
      location: 'Yangon, Myanmar',
      title: 'MIS Manager',
      start: '2014-05',
      end: '2015-05',
      highlights: [
        'Responsible for all IT operations including software and hardware',
        'Managing internal IT & MIS staff and day-to-day microfinance system operations',
        'Responsible for system development, integration, and UAT process',
        'Vendor management and overseas in charge for IT infrastructure',
      ],
    },
    {
      id: 'jobsdb',
      company: 'JOBSDB Pte Ltd.',
      location: 'Singapore',
      title: 'Project Consultant',
      start: '2011-11',
      end: '2014-03',
      highlights: [
        'Consulting and project management for software/IT projects',
        'Project planning, executing, monitoring, and resource allocation',
        'Successfully led NUS TalentConnect, Astar E-Recruitment, Jurong Health E-Recruitment System',
        'IT phone system implementation and vendor management',
      ],
    },
    {
      id: 'telistar',
      company: 'Telistar Solution Pte Ltd.',
      location: 'Singapore',
      title: 'Software Engineer',
      start: '2011-07',
      end: '2011-11',
      highlights: [
        'Requirement gathering, project planning, database design, and development',
        'Successfully led Membership Management System and POS Installment Integration',
        'Microsoft C#, ASP.NET 3.5, and MySQL',
      ],
    },
    {
      id: 'asian-majesty',
      company: 'Asian Majesty Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Software Engineer',
      start: '2008-01',
      end: '2011-06',
      highlights: [
        'Requirement gathering, software design, database design, and outsourcing development',
        'Document Management System, Online Library Search, Hotel Project, POS, Training Center Admin',
        'Microsoft C#, ASP.NET 2.0–4.5, and MS SQL 2005/2008',
      ],
    },
    {
      id: 'durosoft',
      company: 'Durosoft Ltd.',
      location: 'Yangon, Myanmar',
      title: 'Web Application Developer / Programmer',
      start: '2007-01',
      end: '2008-01',
      highlights: [
        'Design, develop, test, and deploy web applications',
        'Groupware/Collaboration, Student Administration System, Payroll System',
        'Microsoft C#, ASP.NET 2.0, PHP, MS SQL 2005, and MySQL',
      ],
    },
  ],
  skillCategories: [
    { axis: 'Leadership', value: 95 },
    { axis: 'Development', value: 88 },
    { axis: 'Project Mgmt', value: 92 },
    { axis: 'Data & BI', value: 85 },
    { axis: 'Infrastructure', value: 87 },
    { axis: 'Cloud & Integration', value: 82 },
  ],
  skills: [
    { name: 'Jira / Trello / MS Project', category: 'Project Mgmt' },
    { name: 'MS SQL / MySQL / BigQuery', category: 'Data & BI' },
    { name: 'Power BI / Tableau', category: 'Data & BI' },
    { name: 'Python / C# / ASP.NET / PHP', category: 'Development' },
    { name: 'JavaScript / jQuery / Ajax', category: 'Development' },
    { name: 'Windows Server / Ubuntu', category: 'Infrastructure' },
    { name: 'Cisco / Fortigate / Ubiquiti', category: 'Infrastructure' },
    { name: 'Office 365 / Google Suite', category: 'Cloud & Integration' },
    { name: 'UML / OOA&D / UI Design', category: 'Development' },
    { name: 'VS Code / Visual Studio', category: 'Development' },
  ],
  projects: [
    {
      name: 'Finflux Core Banking System',
      domain: 'FinTech',
      description: 'Led end-to-end implementation of core banking platform for microfinance operations at Hana Microfinance.',
    },
    {
      name: 'ERP Cloud Migration',
      domain: 'Enterprise',
      description: 'Successfully led Project Fusion ERP Swap and on-premise to cloud ERP migration at Atom Myanmar.',
    },
    {
      name: 'Telecom Selfcare App',
      domain: 'Mobile',
      description: 'Customer-facing mobile selfcare application serving 1.7M users with 24/7 zero-downtime operations.',
    },
    {
      name: 'Data Lake Platform (POC)',
      domain: 'Data',
      description: 'Proof-of-concept data lake platform alongside Solarwind Ticketing Management System at Maha Microfinance.',
    },
    {
      name: 'NUS TalentConnect',
      domain: 'Enterprise',
      description: 'E-recruitment and talent management system delivered for National University of Singapore.',
    },
    {
      name: 'Kredits Loan Tracking System',
      domain: 'FinTech',
      description: 'Loan tracking system implementation supporting branch expansion at Early Dawn Ltd.',
    },
    {
      name: 'Document Management System',
      domain: 'Enterprise',
      description: 'Full SDLC delivery of document management platform using C#, ASP.NET, and MS SQL.',
    },
    {
      name: 'Membership & POS Integration',
      domain: 'Retail',
      description: 'Membership management and POS installment integration built with C#, ASP.NET, and MySQL.',
    },
  ],
  projectFilters: ['All', 'FinTech', 'Enterprise', 'Mobile', 'Data', 'Retail'],
  education: [
    { degree: 'B.Sc (Hons) Business Information Technology', year: 'February 2011' },
    { degree: 'B.Sc (Physics)', year: 'September 2008' },
    { degree: 'IADCS (International Advanced Diploma in Computer Studies)', year: 'January 2007' },
    { degree: 'IDCS (International Diploma in Computer Studies)', year: 'February 2005' },
  ],
  certifications: [
    { name: 'Google Data Analytics Certificate', year: 'September 2021' },
    { name: 'Microsoft Certified Professional Developer (MCPD)', year: 'June 2011' },
    { name: 'Microsoft Certified Technology Specialist (MCTS)', year: 'May 2009' },
    { name: 'Cisco CCNA', year: 'October 2007' },
  ],
  navLinks: [
    { id: 'hero', label: 'Home' },
    { id: 'about', label: 'About' },
    { id: 'experience', label: 'Experience' },
    { id: 'skills', label: 'Skills' },
    { id: 'projects', label: 'Projects' },
    { id: 'education', label: 'Education' },
    { id: 'contact', label: 'Contact' },
  ],
};
